packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@vueuse/core': ^13.0.0
  es-toolkit: ^1.34.1
  type-fest: ^4.39.0
  vue: ^3.5.13
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.1.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
  conflicts_@arco-design/web-vue_l2_57:
    '@arco-design/web-vue': <2.57
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
